# Generated by Django 4.2.5 on 2023-09-27 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='добавьте файл', upload_to='files/', verbose_name='файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='дата загрузки', verbose_name='дата загрузки')),
                ('processed', models.BooleanField(default=False, help_text='статус обработки', verbose_name='статус обработки')),
            ],
        ),
    ]
